module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    env: {
        node: true,
        browser: true,
        es6: true,
        commonjs: true,
    },
    extends: [
        'eslint:recommended',
        'plugin:@next/next/recommended',
        'plugin:prettier/recommended',
    ],
    parserOptions: {
        ecmaFeatures: {
            jsx: true,
        },
        ecmaVersion: 2020,
        parser: '@typescript-eslint/parser',
    },
    plugins: ['react', 'react-hooks', '@next/eslint-plugin-next', 'prettier'],
    rules: {
        'import/prefer-default-export': 0,
        'no-console': 'warn',
        'no-nested-ternary': 0,
        'no-unused-vars': 'off',
        'no-underscore-dangle': 0,
        'no-unused-expressions': ['error', { allowTernary: true }],
        camelcase: 0,
        'react/self-closing-comp': 1,
        'react/jsx-filename-extension': [
            1,
            { extensions: ['.js', 'jsx', '.ts', '.tsx'] },
        ],
        'react/prop-types': 0,
        'react/destructuring-assignment': 0,
        'react/jsx-no-comment-textnodes': 0,
        'react/jsx-props-no-spreading': 0,
        'react/no-array-index-key': 0,
        'react/no-unescaped-entities': 0,
        'react/require-default-props': 0,
        'react/react-in-jsx-scope': 0,
        'react-hooks/rules-of-hooks': 'error',
        'react-hooks/exhaustive-deps': 'warn',
        'react/jsx-uses-react': 'error',
        'react/jsx-uses-vars': 'error',
        'typescript-eslint/no-unused-vars': 'error',
        'typescript-eslint/no-explicit-any': 'error',
        'linebreak-style': ['error', 'unix'],
        semi: ['error', 'never'],
        'prettier/prettier': ['error', {}, { usePrettierrc: true }],
    },
    settings: {
        react: {
            version: 'detect',
        },
    },
}
